package org.redhat.pocFuse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-23T15:15:12.225-05:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://www.example.org/JBossBankServices/", name = "JBossBankServices")
@XmlSeeAlso({ObjectFactory.class})
public interface JBossBankServices {

    @WebMethod(action = "http://www.example.org/JBossBankServices/getCustomerAccounts")
    @RequestWrapper(localName = "getCustomerAccounts", targetNamespace = "http://www.example.org/JBossBankServices/", className = "org.redhat.pocFuse.GetCustomerAccounts")
    @ResponseWrapper(localName = "getCustomerAccountsResponse", targetNamespace = "http://www.example.org/JBossBankServices/", className = "org.redhat.pocFuse.GetCustomerAccountsResponse")
    @WebResult(name = "Accounts", targetNamespace = "")
    public org.redhat.pocFuse.Accounts getCustomerAccounts(
        @WebParam(name = "customerID", targetNamespace = "")
        int customerID
    );

    @WebMethod(action = "http://www.example.org/JBossBankServices/getAccountBalance")
    @RequestWrapper(localName = "getAccountBalance", targetNamespace = "http://www.example.org/JBossBankServices/", className = "org.redhat.pocFuse.GetAccountBalance")
    @ResponseWrapper(localName = "getAccountBalanceResponse", targetNamespace = "http://www.example.org/JBossBankServices/", className = "org.redhat.pocFuse.GetAccountBalanceResponse")
    @WebResult(name = "accountBalance", targetNamespace = "")
    public double getAccountBalance(
        @WebParam(name = "accountID", targetNamespace = "")
        int accountID
    );
}
