package co.com.rbm.esb.comercio.compra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630262
 * 2017-07-27T13:15:23.313-03:00
 * Generated source version: 3.1.5.redhat-630262
 * 
 */
@WebService(targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", name = "CompraElectronica_MsgSetPortType")
@XmlSeeAlso({co.com.rbm.esb.comercio.ObjectFactory.class, ObjectFactory.class, co.com.rbm.esb.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CompraElectronicaMsgSetPortType {

    @WebMethod
    @WebResult(name = "compraProcesarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraProcesarRespuesta")
    public TipoRespuesta compraProcesar(
        @WebParam(partName = "compraProcesarSolicitud", name = "compraProcesarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/")
        TipoSolicitudCompra compraProcesarSolicitud
    );

    @WebMethod
    @WebResult(name = "compraReversarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraReversarRespuesta")
    public TipoRespuesta compraReversar(
        @WebParam(partName = "compraReversarSolicitud", name = "compraReversarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/")
        TipoSolicitudCompra compraReversarSolicitud
    );
}
